### ISSUE TITLE
Open subpages in new tabs from homepage

### ISSUE THREAD

**Issue by qbaron** [gwu-libraries/academiccommons-theme#29]
When I try to Cmd(⌘)-click (which opens a link in a new tab) an icon on the homepage it still opens in the same tab. I assume this has something to do with the way the links and buttons are created. However, it'd be nice to have these open in new tabs if that's what users specifically would like to do

**Comment by maxstarkenburg** [comment]
Looks like interpreting Cmd on Mac in JavaScript is handled rather differently (even different on different browsers there) than on Windows (where I specifically made Ctrl + click work for opening these divs in new tabs). 

I would have liked to just use `<a>` around the whole thing and let the browser take care of it, but IIRC, since they're made via Views, when I tried to wrap an `<a>` around multiple elements like headers and such in the replacement/rewrite results, Drupal was like "oh, silly, let me rearrange that for you". But maybe I missed some other workaround. Maybe I should just use JS to re-wrap the things with an `<a>`.
